Project 2/commerce/auctions/urls.py
"""Contains urls for all app's views"""
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("user_panel", views.user_panel, name="user_panel"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("<int:auction_id>", views.listing_page, name="listing_page"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("bid", views.bid, name="bid"),
    path("categories", views.categories, name="categories"),
    path("categories/<str:category>", views.categories, name="categories"),
    path("close_auction/<str:auction_id>", views.close_auction, name="close_auction"),
    path("handle_comment/<str:auction_id>", views.handle_comment, name="handle_comment")
]

Project 2/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

handler404 = "auctions.views.handle_not_found"

Project 2/commerce/auctions/models.py
"""Contains all models used in the app."""
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    # User model - inherited from Django implementation
    pass

class Auction(models.Model):
    # Auction model holds all info regarding one auction:
    # * auction's title
    # * auction's description
    # * who is selling
    # * auction's current price
    # * when auction was publicated
    # * what is auction's category
    # * auction's image URL
    # * is auction closed?
    

    # Categories - choices
    MOTORS = "MOT"
    FASHION = "FAS"
    ELECTRONICS = "ELE"
    COLLECTIBLES_ARTS = "ART"
    HOME_GARDES = "HGA"
    SPORT_GOODS = "SPO"
    TOYS = "TOY"
    BUSSINES_INDUSTRIAL = "BUS"
    MUSIC = "MUS"

    CATEGORY = [
        (MOTORS, "Motors"),
        (FASHION, "Fashion"),
        (ELECTRONICS, "Electronic Items"),
        (COLLECTIBLES_ARTS, "Collectibles & Art"),
        (HOME_GARDES, "Home & Garden"),
        (SPORT_GOODS, "Sport Goods"),
        (TOYS, "Toys"),
        (BUSSINES_INDUSTRIAL, "Business & Industry"),
        (MUSIC, "Music"),
    ]

    # Model fields
    # auto: auction_id
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=64, blank=False)
    description = models.TextField(blank=True)
    current_price = models.DecimalField(max_digits=11, decimal_places=2, default=0.0)
    category = models.CharField(max_length=3, choices=CATEGORY, default=MOTORS)
    image_url = models.URLField(blank=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)

    class Meta:
        verbose_name = "auction"
        verbose_name_plural = "auctions"

    def __str__(self):
        return f"Auction id: {self.id}, title: {self.title}, seller: {self.seller}"

class Bid(models.Model):
    # Bid model contains all info about single bid:
    # * price
    # * who bid
    # * when
    # * on what auction

    # Model fields
    # auto: bid_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_date = models.DateTimeField(auto_now_add=True)
    bid_price = models.DecimalField(max_digits=11, decimal_places=2)

    class Meta:
        verbose_name = "bid"
        verbose_name_plural = "bids"

    def __str__(self):
        return f"{self.user} bid {self.bid_price} $ on {self.auction}"

class Comment(models.Model):
    # Comment model contains all info about single comment
    # * content
    # * who posted
    # * when
    # * on what auction
    

    # Model fields
    # auto: comment_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(blank=False)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)
    class Meta:
        verbose_name = "comment"
        verbose_name_plural = "comments"

    def __str__(self):
        return f"Comment {self.id} on auction {self.auction} made by {self.user}"

class Watchlist(models.Model):
    # Watchlist model contains all info about object on watchlist
    # * which auction is on watchlist
    # * on whose watchlist this auction is
    

    # Model field
    # auto: watchlist_id
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")

    class Meta:
        verbose_name = "watchlist"
        verbose_name_plural = "watchlists"
        # Forces to not have auction duplicates for one user
        unique_together = ["auction", "user"]

    def __str__(self):
        return f"{self.auction} on user {self.user} watchlist"

Project 2/commerce/auctions/views.py
"""Contains implementation of all views used in this app"""

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django import forms

# Error exceptions
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError

from .models import User, Auction, Bid, Comment, Watchlist


# ----------------------------------------------------------------------
# ------------------------------  Forms  -------------------------------
# ----------------------------------------------------------------------
class CreateListingForm(forms.ModelForm):
    """Creates form for Auction model."""

    title = forms.CharField(
        label="Title",
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={
                "autocomplete": "off",
                "aria-label": "title",
                "class": "form-control",
            }
        ),
    )
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(
            attrs={
                "placeholder": "Tell more about the product",
                "aria-label": "description",
                "class": "form-control",
            }
        ),
    )
    image_url = forms.URLField(
        label="Image URL",
        required=True,
        widget=forms.URLInput(attrs={"class": "form-control"}),
    )

    category = forms.ChoiceField(
        required=True,
        choices=Auction.CATEGORY,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    current_price = forms.DecimalField(
        label="Price",
        required=True,
        max_digits=11,
        decimal_places=2,
        widget=forms.NumberInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Auction
        fields = ["title", "description", "category", "image_url", "current_price"]


class BidForm(forms.ModelForm):
    """Creates form for Bid model."""

    class Meta:
        model = Bid
        fields = ["bid_price"]
        labels = {"bid_price": _("")}
        widgets = {
            "bid_price": forms.NumberInput(
                attrs={
                    "placeholder": "Bid",
                    "min": 0.01,
                    "max": 100000000000,
                    "class": "form-control",
                }
            )
        }


class CommentForm(forms.ModelForm):
    """Creates form for Comment model."""

    class Meta:
        model = Comment
        fields = ["comment"]
        labels = {"comment": _("")}
        widgets = {
            "comment": forms.Textarea(
                attrs={
                    "placeholder": "Comment here",
                    "class": "form-control",
                    "rows": 1,
                }
            )
        }


# ----------------------------------------------------------------------
# ------------------------------  Views  -------------------------------
# ----------------------------------------------------------------------
def index(request):
    """Main view: shows all listings."""
    # Get all auctions descending
    auctions = Auction.objects.filter(closed=False).order_by("-publication_date")

    return render(request, "auctions/index.html", {"auctions": auctions})


@login_required(login_url="auctions:login")
def user_panel(request):
    """User Panel view: shows all auctions that user:
    * is currently selling
    * sold
    * is currently bidding
    * won
    """
    # Helpers
    all_distinct_bids = (
        Bid.objects.filter(user=request.user.id)
        .values_list("auction", flat=True)
        .distinct()
    )
    won = []

    # Get auctions currently being sold by the user
    selling = (
        Auction.objects.filter(closed=False, seller=request.user.id)
        .order_by("-publication_date")
        .all()
    )

    # Get auction sold by the user
    sold = (
        Auction.objects.filter(closed=True, seller=request.user.id)
        .order_by("-publication_date")
        .all()
    )

    # Get auctions currently being bid by the user
    bidding = Auction.objects.filter(closed=False, id__in=all_distinct_bids).all()

    # Get auctions won by the user
    for auction in Auction.objects.filter(closed=True, id__in=all_distinct_bids).all():
        highest_bid = (
            Bid.objects.filter(auction=auction.id).order_by("-bid_price").first()
        )

        if highest_bid.user.id == request.user.id:
            won.append(auction)

    return render(
        request,
        "auctions/user_panel.html",
        {"selling": selling, "sold": sold, "bidding": bidding, "won": won},
    )


@login_required(login_url="auctions:login")
def create_listing(request):
    """Create Listing view: allows to add new listing through a form."""
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        if form.is_valid():
            # Get all data from the form
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            category = form.cleaned_data["category"]
            image_url = form.cleaned_data["image_url"]
            current_price = form.cleaned_data["current_price"]

            # Save a record
            auction = Auction(
                seller=User.objects.get(pk=request.user.id),
                title=title,
                description=description,
                category=category,
                image_url=image_url,
                current_price=current_price,
            )
            auction.save()
        else:
            return render(request, "auctions/create_listing.html", {"form": form})

    return render(
        request,
        "auctions/create_listing.html",
        {
            "form": CreateListingForm(),
        },
    )


def listing_page(request, auction_id):
    """Listing Page view: shows detailed page of a single auction."""
    # Get current auction if exists
    try:
        auction = Auction.objects.get(pk=auction_id)
    except Auction.DoesNotExist:
        return render(
            request,
            "auctions/error_handling.html",
            {"code": 404, "message": "Auction id doesn't exist"},
        )

    # Get info about bids
    bid_amount = Bid.objects.filter(auction=auction_id).count()
    highest_bid = Bid.objects.filter(auction=auction_id).order_by("-bid_price").first()

    # Show auction only to the winner and the seller if closed
    if auction.closed:
        if highest_bid is not None:
            winner = highest_bid.user

            # Diffrent view for winner, seller and other users
            if request.user.id == auction.seller.id:
                return render(
                    request,
                    "auctions/sold.html",
                    {"auction": auction, "winner": winner},
                )
            elif request.user.id == winner.id:
                return render(request, "auctions/bought.html", {"auction": auction})
        else:
            if request.user.id == auction.seller.id:
                return render(
                    request, "auctions/closed_no_offer.html", {"auction": auction}
                )

        return HttpResponse("Error - auction no longer available")
    else:
        # If user logged in, check if auction already in watchlist
        if request.user.is_authenticated:
            watchlist_item = Watchlist.objects.filter(
                auction=auction_id, user=User.objects.get(id=request.user.id)
            ).first()

            if watchlist_item is not None:
                on_watchlist = True
            else:
                on_watchlist = False
        else:
            on_watchlist = False

        # Get all the comments
        comments = Comment.objects.filter(auction=auction_id)

        # Check who has made the highest bid
        if highest_bid is not None:
            if highest_bid.user == request.user.id:
                bid_message = "Your bid is the highest bid"
            else:
                bid_message = "Highest bid made by " + highest_bid.user.username
        else:
            bid_message = None

        return render(
            request,
            "auctions/listing_page.html",
            {
                "auction": auction,
                "bid_amount": bid_amount,
                "bid_message": bid_message,
                "on_watchlist": on_watchlist,
                "comments": comments,
                "bid_form": BidForm(),
                "comment_form": CommentForm(),
            },
        )


@login_required(login_url="auctions:login")
def watchlist(request):
    """Watchlist views: shows all auctions that are on user's watchlist."""
    # Save info about the auction and go back to auction's page
    if request.method == "POST":
        # Info about the auction
        auction_id = request.POST.get("auction_id")

        # Make sure that auction exists
        try:
            auction = Auction.objects.get(pk=auction_id)
            user = User.objects.get(id=request.user.id)
        except Auction.DoesNotExist:
            return render(
                request,
                "auctions/error_handling.html",
                {"code": 404, "message": "Auction id doesn't exist"},
            )

        # Add/delete from watchlist logic
        if request.POST.get("on_watchlist") == "True":
            # Delete it from watchlist model
            watchlist_item_to_delete = Watchlist.objects.filter(
                user=user, auction=auction
            )
            watchlist_item_to_delete.delete()
        else:
            # Save it to watchlist model
            try:
                watchlist_item = Watchlist(user=user, auction=auction)
                watchlist_item.save()

Project 2/commerce/auctions/templates/auctions/bought.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>Congratulations!</h1> 
    <h3>You bough item: {{ auction.title }} for ₹ {{ auction.current_price }}.</h3>
    Please contect the seller <strong>{{ auction.seller.username }}</strong> and finalize your purchase.

{% endblock %}

Project 2/commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container">
    <div class="sub-title">Create Listing</div>

    <form action="{% url 'auctions:create_listing' %}", method="POST">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_title">{{ form.title.label }}:</label>
            {{ form.title }}
        </div>
        <div class="form-group mb-3">
            <label for="id_description">{{ form.description.label }}:</label>
            {{ form.description }}
        </div>
        <div class="form-group mb-3">
            <label for="id_category">{{ form.category.label }}:</label>
            {{ form.category }}
        </div>
        <div class="form-group mb-3">
            <label for="id_current_price">{{ form.current_price.label }}:</label>
            {{ form.current_price }}
        </div>
        <div class="form-group mb-3">
            <label for="id_image_url">{{ form.image_url.label }}:</label>
            {{ form.image_url }}
        </div>
        <button type="submit" class="btn btn-primary" aria-label="submit">Submit</button>
    </form>
</div>
{% endblock %}

Project 2/commerce/auctions/templates/auctions/layout.html
{% load static %}

{% url 'auctions:index' as  index %}
{% url 'auctions:categories' category='MOT' as  motors %}
{% url 'auctions:categories' category='FAS' as  fashion %}
{% url 'auctions:categories' category='ELE' as  electronics %}
{% url 'auctions:categories' category='ART' as  art %}
{% url 'auctions:categories' category='HGA' as  home %}
{% url 'auctions:categories' category='SPO' as  sport %}
{% url 'auctions:categories' category='TOY' as  toys %}
{% url 'auctions:categories' category='BUS' as  business %}
{% url 'auctions:categories' category='MUS' as  music %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link rel="icon" href="https://img.icons8.com/plasticine/2x/auction.png" type = "image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7faee5c6e1.js" crossorigin="anonymous"></script>
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    <link href="{% static 'auctions/sidebar.css' %}" rel="stylesheet">
    <script defer src="{% static 'auctions/sidebar.js' %}"></script>
</head>

<body>
    <body id="body-pd">
        <!-- Sidebar from Bootstrap -->
        <header class="header" id="header">
            <div class="header_toggle">
                <i class='fas fa-angle-right' id="header-toggle"></i>
            </div>
            <div class="nav-buttons">
                {% if user.is_authenticated %}
                    <button type="button" class="btn btn-primary">
                        <a class="nav-link" href="{% url 'auctions:user_panel' %}">User Panel</a>
                    </button>
                    <button type="button" class="btn btn-primary">
                        <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listing</a>
                    </button>
                    <button type="button" class="btn btn-primary">
                        <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                    </button>
                    <button type="button" class="btn btn-danger">
                        <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                    </button>
                {% else %}
                    <button type="button" class="btn btn-primary">
                        <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                    </button>
                    <button type="button" class="btn btn-primary">
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </button>
                {% endif %}
            </div>
        </header>
        <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div> 
                    <div class="nav_logo hide-inner">
                        <span class="nav_categories">Categories</span>
                    </div>
                    <div class="nav_list">
                        <a href="{{ index }}" class="nav_link {% if request.path == index %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-border-all" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <rect x="4" y="4" width="16" height="16" rx="2"></rect>
                                <line x1="4" y1="12" x2="20" y2="12"></line>
                                <line x1="12" y1="4" x2="12" y2="20"></line>
                             </svg>
                            <span class="nav_name">All</span> 
                        </a>
                        <a href="{{ motors }}" class="nav_link {% if request.path == motors %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-car" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <circle cx="7" cy="17" r="2"></circle>
                                <circle cx="17" cy="17" r="2"></circle>
                                <path d="M5 17h-2v-6l2 -5h9l4 5h1a2 2 0 0 1 2 2v4h-2m-4 0h-6m-6 -6h15m-6 0v-5"></path>
                             </svg>
                            <span class="nav_name">Motors</span> 
                        </a>
                        <a href="{{ sport }}" class="nav_link {% if request.path == sport %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-bike" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <circle cx="5" cy="18" r="3"></circle>
                                <circle cx="19" cy="18" r="3"></circle>
                                <polyline points="12 19 12 15 9 12 14 8 16 11 19 11"></polyline>
                                <circle cx="17" cy="5" r="1"></circle>
                             </svg>
                            <span class="nav_name">Sport Goods</span>
                        </a>
                        <a href="{{ electronics }}" class="nav_link {% if request.path == electronics %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-devices-2" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M10 15h-6a1 1 0 0 1 -1 -1v-8a1 1 0 0 1 1 -1h6"></path>
                                <rect x="13" y="4" width="8" height="16" rx="1"></rect>
                                <line x1="7" y1="19" x2="10" y2="19"></line>
                                <line x1="17" y1="8" x2="17" y2="8.01"></line>
                                <circle cx="17" cy="16" r="1"></circle>
                                <line x1="9" y1="15" x2="9" y2="19"></line>
                             </svg>
                            <span class="nav_name">Electronic Items</span> 
                        </a>
                        <a href="{{ music }}" class="nav_link {% if request.path == music %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-music" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <circle cx="6" cy="17" r="3"></circle>
                                <circle cx="16" cy="17" r="3"></circle>
                                <polyline points="9 17 9 4 19 4 19 17"></polyline>
                                <line x1="9" y1="8" x2="19" y2="8"></line>
                             </svg>
                            <span class="nav_name">Music</span>
                        </a>
                        <a href="{{ home }}" class="nav_link {% if request.path == home %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <polyline points="5 12 3 12 12 3 21 12 19 12"></polyline>
                                <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                             </svg>
                            <span class="nav_name">Home & Garden</span>
                        </a>
                        <a href="{{ fashion }}" class="nav_link {% if request.path == fashion %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-shirt" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M15 4l6 2v5h-3v8a1 1 0 0 1 -1 1h-10a1 1 0 0 1 -1 -1v-8h-3v-5l6 -2a3 3 0 0 0 6 0"></path>
                             </svg>
                            <span class="nav_name">Fashion</span> 
                        </a>

                        <a href="{{ toys }}" class="nav_link {% if request.path == toys %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-puzzle" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M4 7h3a1 1 0 0 0 1 -1v-1a2 2 0 0 1 4 0v1a1 1 0 0 0 1 1h3a1 1 0 0 1 1 1v3a1 1 0 0 0 1 1h1a2 2 0 0 1 0 4h-1a1 1 0 0 0 -1 1v3a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-1a2 2 0 0 0 -4 0v1a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1h1a2 2 0 0 0 0 -4h-1a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1"></path>
                             </svg>
                            <span class="nav_name">Toys</span>
                        </a>       
                        <a href="{{ art }}" class="nav_link {% if request.path == art %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-palette" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M12 21a9 9 0 1 1 0 -18a9 8 0 0 1 9 8a4.5 4 0 0 1 -4.5 4h-2.5a2 2 0 0 0 -1 3.75a1.3 1.3 0 0 1 -1 2.25"></path>
                                <circle cx="7.5" cy="10.5" r=".5" fill="currentColor"></circle>
                                <circle cx="12" cy="7.5" r=".5" fill="currentColor"></circle>
                                <circle cx="16.5" cy="10.5" r=".5" fill="currentColor"></circle>
                             </svg>
                            <span class="nav_name">Collectibles & Art</span>
                        </a>                  
                        <a href="{{ business }}" class="nav_link {% if request.path == business %} active {% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-briefcase" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <rect x="3" y="7" width="18" height="13" rx="2"></rect>
                                <path d="M8 7v-2a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v2"></path>
                                <line x1="12" y1="12" x2="12" y2="12.01"></line>
                                <path d="M3 13a20 20 0 0 0 18 0"></path>
                             </svg>
                            <span class="nav_name">Business & Industry</span>
                        </a>                        

                    </div>
                </div>
            </nav>
        </div>
        <div>
            <div class="main-title">Auctions</div>
            {% if user.is_authenticated %}
            Signed in as <strong>{{ user.username }}</strong>
            {% endif %}
            <hr>
        </div>
        <div class="height-100 bg-light">
            {% block body %}
            {% endblock %}
        </div>
    </body>

</html>

Project 2/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="container">
        <div class="sub-title">Login</div>
    
        {% if message %}
            <div class="mb-3">{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'auctions:login' %}" method="post" class="mb-3">
            {% csrf_token %}
            <div class="mb-3">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
        Don't have an account? <a class="register-here" href="{% url 'auctions:register' %}">Register here.</a>
    </div>

{% endblock %}

Project 2/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="container">
        <div class="sub-title">Register</div>

        {% if message %}
            <div class="mb-3">{{ message }}</div>
        {% endif %}

        <form action="{% url 'auctions:register' %}" method="post" class="mb-3">
            {% csrf_token %}
            <div class="mb-3">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="mb-3">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="mb-3">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>

        Already have an account? <a class="register-here" href="{% url 'auctions:login' %}">Log In here.</a>
        </div>
{% endblock %}